apiVersion: apps/v1
kind: Deployment
metadata:
  name: plataforma-deployment
  labels:
    app: plataforma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plataforma
  template:
    metadata:
      labels:
        app: plataforma
    spec:
      containers:
        - name: plataforma
          image: carlodelgado/plataforma
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: plataforma-loadbalancer-service
  labels:
    app: plataforma
spec:
  type: LoadBalancer
  selector:
    app: plataforma
  ports:
    - port: 80
      targetPort: 80



