apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatar-deployment
  labels:
    app: avatar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avatar
  template:
    metadata:
      labels:
        app: avatar
    spec:
      containers:
        - name: avatar
          image: carlodelgado/avatar
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: avatar-loadbalancer-service
  labels:
    app: avatar
spec:
  type: LoadBalancer
  selector:
    app: avatar
  ports:
    - port: 80
      targetPort: 80



